version: '3.7'
services:
  sshd:
    image: hermsi/alpine-sshd
    container_name: sshd.local
    environment: 
      - ROOT_PASSWORD=root
    volumes: 
      - ./sshd:/etc/ssh
    ports:
      - "3333:22"
  apache:
    image: httpd:latest
    container_name: apache.local
  webdav:
    image: bytemark/webdav
    container_name: webdav.local
    restart: always
    environment:
      AUTH_TYPE: Digest
      USERNAME: admin
      PASSWORD: admin
    volumes:
      - ./dav:/var/lib/dav